#!/usr/bin/env bash
#
# symlink files to ~
# so they are centralized here
#
# (heavily) Inspired by Dave Eddy of YSAP
# See: github.com/bahamas10/dotfiles

symlink() {
    printf '%55s -> %s\n' "${1/#$HOME/~}" "${2/#$HOME/~}"
    ln -nsf "$@"
}

# don't forget to add dotfiles here!
dotfiles=(
    vimrc
    vim/my-plugins
    vim/autoload
    vim/plugins
)

for f in "${dotfiles[@]}"; do
    [[ -d ~/.$f && ! -L ~/.$f ]] && rm -r ~/."$f"
    symlink "$PWD/$f" ~/."$f"
done

# run plug install for vim
if [[ -t 1 ]]; then
    vim '+PlugInstall --sync' +qa
fi
